#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Application-properties, Attachment, Auditing
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/applicationPropertiesAttachmentAuditing.md
  - title: Filter, IssueLinkType, Jql, LicenseValidator
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/filterIssuelinktypeJqlLicensevalidator.md
  - title: Group, Project, Myself
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/groupProjectMyself.md
  - title: Issue Part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/issuePartThree.md
  - title: Issue Part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/issuePartTwo.md
  - title: IssueLink, Issue Part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/issuelinkIssuePartOne.md
  - title: Screens, Projectvalidate, Reindex, Resolution
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/screensProjectvalidateReindexResolution.md
  - title: User
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/user.md
  - title: Version
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/version.md
  - title: Workflow
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/workflow.md
  - title: Workflowscheme
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Jira/production/notebooks/api/workflowscheme.md
