#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): https://parse.com/docs/rest
(library.extraResources):
  - title: Classes and cloud functions
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Parse/master/notebooks/classesAndCloudFunctions.md
  - title: Files, events, push notifications, installations
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Parse/master/notebooks/filesEventsPushNotificationsInstallations.md
  - title: Roles
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Parse/master/notebooks/roles.md
  - title: Users
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Parse/master/notebooks/users.md
