#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Gists
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/gists.md
  - title: Gitignore, markdown, networks, legacy, emojis
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/gitignoreMarkdownNetworksLegacyEmojis.md
  - title: Repos part 5
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartFive.md
  - title: Repos part 4
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartFour.md
  - title: Repos part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartOne.md
  - title: Repos part 6
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartSix.md
  - title: Repos part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartThree.md
  - title: Repos part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/reposPartTwo.md
  - title: Search, events, feeds, meta, notifications
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/searchEventsFeedsMetaNotifications.md
  - title: User
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/user.md
  - title: Users, orgs and teams
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GitHub/production/notebooks/api/usersOrgsAndTeams.md
