#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): http://instagram.com/developer​
(library.extraResources):
  - title: Instagram RAML API Notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Instagram/master/notebooks/instagramNotebook.md
