#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/Zendesk/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://developer.zendesk.com
(library.extraResources):
  - title: Account, uploads, attachments, locales
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/accountUploadsAttachmentsLocales.md
  - title: Apps
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/apps.md
  - title: Dynamic content, forums, automations, categories
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/dynamicContentForumsAutomationsCategories.md
  - title: End user
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/endUser.md
  - title: Help center: articles, questions, translations
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/hcArticlesQuestionsTranslationsVotesAnswers.md
  - title: Help center: section, locale
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/hcSectionLocaleCategiesUsers.md
  - title: Incremental
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/incremental.md
  - title: Macros, ticket
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/macrosTicket.md
  - title: Merge users
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/mergeUsers.md
  - title: Organizations, organization field and subscription
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/organizationsOrganizationFieldAndSubscription.md
  - title: Phone numbers
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/phoneNumbers.md
  - title: Requests, search, portal, sharing agreements
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/requestsSearchPortalSharingAgreements.md
  - title: Set user password, change own password
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/setUserPasswordChangeOwnPassword.md
  - title: Suspended ticket, mark as spam, activities
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/suspendedTicketMarkAsSpamActivities.md
  - title: Twitter
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/twitter.md
  - title: Users, job statuses
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/usersJobStatuses.md
  - title: Views, oauth, bookmarks
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/viewsOauthBookmarks.md
  - title: Voice, ticket metric
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/voiceTicketMetric.md
  - title: Zendesk targets, problems, exports, import
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zendesk/master/notebooks/zendeskTargetsProblemsExportsImport.md
