#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: GMail media upload
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleMail/production/notebooks/uploadApi/gmailMediaUpload.md
