#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): https://bufferapp.com/developers/api
(library.extraResources):
  - title: Bufferapp API Notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Bufferapp/master/notebooks/bufferappApiNotebook.md
