#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/GoogleContacts/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://developers.google.com/google-apps/contacts/v3/
(library.extraResources):
  - title: Google Contacts (cloned)
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleContacts/master/notebooks/notebook.md
