#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/Twilio/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): www.twilio.com/docs/api/rest
(library.extraResources):
  - title: Add incoming numbers
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/addIncomingNumbers.md
  - title: Applications, Notifications, Incoming Numbers
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/applicationsNotificationsIncomingNumbers.md
  - title: Conferences
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/conferences.md
  - title: Connect Apps, Authorized Connect Apps
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/connectAppsAuthorizedConnectAppsAndUsage.md
  - title: Dangerous methods
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/dangerousMethods.md
  - title: Outgoing Caller Id, Available Numbers and Calls
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/outgoingCallerIdAvailablePhoneNumbersCalls.md
  - title: Queues
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/queues.md
  - title: Recordings
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/recordings.md
  - title: SIP CredentialLists
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/sipCredentiallists.md
  - title: SIP IpAccessControlLists
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/sipIpaccesscontrollists.md
  - title: SMS, Messages, making Calls
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/smsMessagesMakingCalls.md
  - title: Transcriptions
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twilio/master/notebooks/transcriptions.md
