#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Attachments, google attachments
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PivotalTracker/production/notebooks/api/attachmentsGoogleAttachments.md
  - title: Projects part 1, me, my, people
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PivotalTracker/production/notebooks/api/projectsPartOneMeMyPeople.md
  - title: Projects part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PivotalTracker/production/notebooks/api/projectsPartThree.md
  - title: Projects part 2, stories, accounts, source commits
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PivotalTracker/production/notebooks/api/projectsPartTwoStoriesAccountsSourceCommits.md
