#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): http://www.zillow.com/howto/api/APIOverview.htm
(library.extraResources):
  - title: Zillow (part 2 -- mortgage)
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zillow/master/notebooks/mortgageOutdated.md
  - title: Zillow Notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Zillow/master/notebooks/zillowNotebook.md
