#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): https://www.smartsheet.com/developers/api-documentation​
(library.extraResources):
  - title: Folder, templates, report, users, groups, search
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/SmartSheet/master/notebooks/folderTemplatesReportUsersGroupsSear.md
  - title: Home, favorites, workspaces
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/SmartSheet/master/notebooks/homeFavoritesWorkspaces.md
  - title: Sheet/attachments, sheet/publish, sheet/column
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/SmartSheet/master/notebooks/sheetAttachmentsSheetPublishSheetColumn.md
  - title: Sheet/version, sheet/emails, sheet/columns
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/SmartSheet/master/notebooks/sheetVersionSheetEmailsSheetColumns.md
