#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Escalation policies
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/escalationPolicies.md
  - title: Incidents, log entries, alerts and reports
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/incidentsLogEntriesAlertsAndReports.md
  - title: Maintenance windows
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/maintenanceWindows.md
  - title: Schedules
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/schedules.md
  - title: Services
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/services.md
  - title: Users
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/PagerDuty/production/notebooks/pagerDuty/users.md
