#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: About, changes, permissionIds, app
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleDrive/production/notebooks/api/aboutChangesPermissionIdsAppChannels.md
  - title: File. part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleDrive/production/notebooks/api/filePartOne.md
  - title: File. part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleDrive/production/notebooks/api/filePartTwo.md
  - title: Upload API, File revisions
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleDrive/production/notebooks/api/uploadApiFileRevisions.md
  - title: Watch
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleDrive/production/notebooks/api/watch.md
