#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): http://msdn.microsoft.com/en-us/library/azure/dd179423.aspx​
(library.extraResources):
  - title: Account Properties and Operations on Tables
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/AzureTableStorage/master/notebooks/accountPropertiesAndOperationsOnTables.md
  - title: Operations on Entities
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/AzureTableStorage/master/notebooks/operationsOnEntities.md
