#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Files
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Box/raml1.0/notebooks/boxAPI/files.md
  - title: Folders and collaborations
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Box/raml1.0/notebooks/boxAPI/foldersAndCollaborations.md
  - title: Tasks, task assignments, events and searches
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Box/raml1.0/notebooks/boxAPI/tasksTaskAssignmentsEventsAndSearches.md
  - title: Users, groups and memberships
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Box/raml1.0/notebooks/boxAPI/usersGroupsAndMemberships.md
