#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/StackExchange/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://api.stackexchange.com/docs​
(library.extraResources):
  - title: Access-tokens, apps, errors, filters, inbox
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/StackExchange/master/notebooks/accessTokensAppsErrorsFiltersInbox.md
  - title: Events, info, posts, privileges, questions
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/StackExchange/master/notebooks/eventsInfoPostsPrivilegesQuestions.md
  - title: Me
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/StackExchange/master/notebooks/me.md
  - title: Users
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/StackExchange/master/notebooks/users.md
