#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/Stripe/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://stripe.com/docs
(library.extraResources):
  - title: Accounts, customers, plans and coupons
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Stripe/master/notebooks/accountsCustomersPlansAndCoupons.md
  - title: Charges, invoices and invoice items
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Stripe/master/notebooks/chargesInvoicesAndInvoiceItems.md
  - title: Transfers, recepients, balance, events, tokens
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Stripe/master/notebooks/transfersRecepientsBalanceEventsTokens.md
