#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Airlines, airports
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/FlightStats/production/notebooks/api/airlinesAirports.md
  - title: Alerts, Delay Index, FIDS, Ratings
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/FlightStats/production/notebooks/api/alertsDelayIndexesSchedulesWeatherRatingsFIDS.md
