#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/Slack/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://api.slack.com/
(library.extraResources):
  - title: Slack API notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Slack/master/notebooks/slackApiNotebook.md
