#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/SlideShare/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): http://www.slideshare.net/developers/documentation
(library.extraResources):
  - title: Slideshare API Notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/SlideShare/master/notebooks/slideshareApiNotebook.md
