#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Friends/Followers
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/friendsFollowers.md
  - title: List
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/list.md
  - title: Saved Searches, Geo, Trends, Help, Apps
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/savedsearchesGeoTrendsHelpApplication.md
  - title: Search, DMs, Blocks, Favorites
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/searchesdirectMessagesblocksfavourites.md
  - title: Status
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/statuses.md
  - title: Users
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitter/production/notebooks/api/users.md
