#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Buckets part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/AmazonS3/production/notebooks/amazonS3Services/bucketsPartThree.md
