#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): https://raw.githubusercontent.com/apiregistry/registry/master/projects/Twitch/logo.png
(library.specAuthor): mulesoft.com
(library.devPortal): https://github.com/justintv/Twitch-API/blob/master/README.md
(library.extraResources):
  - title: Twitch.tv API notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Twitch/master/notebooks/twitchApiNotebook.md
