#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Messages and Drafts
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleMail/raml1.0/notebooks/api/messagesAndDrafts.md
  - title: Threads, History and Labels
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/GoogleMail/raml1.0/notebooks/api/threadsHistoryAndLabels.md
