#%RAML 1.0 Overlay
extends: boxApi.raml
uses:
  library: https://raw.githubusercontent.com/apiregistry/storage/master/libraries/specOverlayTypesLibrary.raml
(library.highLevelApiDescription): 
(library.apiLogo): 
(library.specAuthor): mulesoft.com
(library.devPortal): 
(library.extraResources):
  - title: Auxilliary notebook
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/auxilliaryNotebook.md
  - title: Graph. App part 1, user part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphAppPartOneUserPartThree.md
  - title: Graph. App part 2, group part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphAppPartTwoGroupPartOne.md
  - title: Graph. Friendlist, group part 2, link, group doc
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphFriendlistGroupPartTwoLinkGroupDoc.md
  - title: Graph. heckins, domains, events
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphHeckinsDomainsEvents.md
  - title: Graph. Message, user part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphMessageUserPartOne.md
  - title: Graph. Page, conversations, milestone, offer
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphPageConversationsMilestoneOffer.md
  - title: Graph. Post, object, thread, user part 4
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphPostObjectThreadUserPartFour.md
  - title: Graph. Status, user part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphStatusUserPartTwo.md
  - title: Graph. Test user
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphTestUser.md
  - title: Graph. User part 5, albums, photo, comment
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphUserPartFiveAlbumsPhotoComment.md
  - title: Graph. Video, order, review, search, request
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/graphVideoOrderReviewSearchRequest.md
  - title: Open graph, actions part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/openGraphActionsPartOne.md
  - title: Open graph, actions part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/openGraphActionsPartTwo.md
  - title: Open graph, objects part 1
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/openGraphObjectsPartOne.md
  - title: Open graph, objects part 3
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/openGraphObjectsPartThree.md
  - title: Open graph, objects part 2
    type: notebook
    uri: https://raw.githubusercontent.com/raml-apis/Facebook/production/notebooks/api/openGraphObjectsPartTwo.md
